//GET ALL PATIENTS
export const PATIENT_REQUEST = 'PATIENT_REQUEST'
export const PATIENT_SUCCESS = 'PATIENT_SUCCESS'
export const PATIENT_FALIURE = 'PATIENT_FALIURE'

//GET A SINGLE PATIENT
export const SINGLE_PATIENT_REQUEST = 'SINGLE_PATIENT_REQUEST'
export const SINGLE_PATIENT_SUCCESS = 'SINGLE_PATIENT_SUCCESS'
export const SINGLE_PATIENT_FALIURE = 'SINGLE_PATIENT_FALIURE'

// CREATE A PATIENTS
export const CREATE_PATIENT_REQUEST = 'CREATE_PATIENT_REQUEST'
export const CREATE_PATIENT_SUCCESS = 'CREATE_PATIENT_SUCCESS'
export const CREATE_PATIENT_FALIURE = 'CREATE_PATIENT_FALIURE'

