//GET ALL serviceS
export const SERVICE_REQUEST = 'SERVICE_REQUEST'
export const SERVICE_SUCCESS = 'SERVICE_SUCCESS'
export const SERVICE_FALIURE = 'SERVICE_FALIURE'

//GET A SINGLE service
export const SINGLE_SERVICE_REQUEST = 'SINGLE_SERVICE_REQUEST'
export const SINGLE_SERVICE_SUCCESS = 'SINGLE_SERVICE_SUCCESS'
export const SINGLE_SERVICE_FALIURE = 'SINGLE_SERVICE_FALIURE'

// CREATE A serviceS
export const CREATE_SERVICE_REQUEST = 'CREATE_SERVICE_REQUEST'
export const CREATE_SERVICE_SUCCESS = 'CREATE_SERVICE_SUCCESS'
export const CREATE_SERVICE_FALIURE = 'CREATE_SERVICE_FALIURE'

