//GET ALL LAB REQUEST
export const LABORATORY_REQUEST = 'LABORATORY_REQUEST'
export const LABORATORY_SUCCESS = 'LABORATORY_SUCCESS'
export const LABORATORY_FALIURE = 'LABORATORY_FALIURE'


//CREATE A LAB REQUEST
export const CREATE_LABORATORY_REQUEST = 'CREATE_LABORATORY_REQUEST'
export const CREATE_LABORATORY_SUCCESS = 'CREATE_LABORATORY_SUCCESS'
export const CREATE_LABORATORY_FALIURE = 'CREATE_LABORATORY_FALIURE'