//GET ALL LAB REQUEST
export const LABORATORY_REQUEST = 'LABORATORY_REQUEST'
export const LABORATORY_SUCCESS = 'LABORATORY_SUCCESS'
export const LABORATORY_FALIURE = 'LABORATORY_FALIURE'

//FETCH A SINGLE LAB REQUEST
export const SINGLE_LABORATORY_REQUEST = 'SINGLE_LABORATORY_REQUEST'
export const SINGLE_LABORATORY_SUCCESS = 'SINGLE_LABORATORY_SUCCESS'
export const SINGLE_LABORATORY_FALIURE = 'SINGLE_LABORATORY_FALIURE'

//CREATE A SINGLE LAB REQUEST
export const CREATE_LABORATORY_REQUEST = 'CREATE_LABORATORY_REQUEST'
export const CREATE_LABORATORY_SUCCESS = 'CREATE_LABORATORY_SUCCESS'
export const CREATE_LABORATORY_FALIURE = 'CREATE_LABORATORY_FALIURE'

//CREATE A SINGLE INVESTIGATION REQUEST
export const CREATE_INVESTIGATION_REQUEST = 'CREATE_INVESTIGATION_REQUEST'
export const CREATE_INVESTIGATION_SUCCESS = 'CREATE_INVESTIGATION_SUCCESS'
export const CREATE_INVESTIGATION_FALIURE = 'CREATE_INVESTIGATION_FALIURE'

//GET ANTIBIOTICS
export const ANTIBIOTICS_REQUEST = 'ANTIBIOTICS_REQUEST'
export const ANTIBIOTICS_SUCCESS = 'ANTIBIOTICS_SUCCESS'
export const ANTIBIOTICS_FALIURE = 'ANTIBIOTICS_FALIURE'

//CREATE ANTIBIOTICS
export const CREATE_ANTIBIOTICS_REQUEST = 'CREATE_ANTIBIOTICS_REQUEST'
export const CREATE_ANTIBIOTICS_SUCCESS = 'CREATE_ANTIBIOTICS_SUCCESS'
export const CREATE_ANTIBIOTICS_FALIURE = 'CREATE_ANTIBIOTICS_FALIURE'
