//GET CURRENT LOGIN USER
export const USER_REQUEST = 'USER_REQUEST'
export const USER_SUCCESS = 'USER_SUCCESS'
export const USER_FALIURE = 'USER_FALIURE'

//GET ALL USER
export const ALL_USER_REQUEST = 'ALL_USER_REQUEST'
export const ALL_USER_SUCCESS = 'ALL_USER_SUCCESS'
export const ALL_USER_FALIURE = 'ALL_USER_FALIURE'