//GET ALL INVOICE
export const INVOICE_REQUEST = 'INVOICE_REQUEST'
export const INVOICE_SUCCESS = 'INVOICE_SUCCESS'
export const INVOICE_FALIURE = 'INVOICE_FALIURE'

//GET A SINGLE INVOICE
export const INVOICE_SINGLE_REQUEST = 'INVOICE_SINGLE_REQUEST'
export const INVOICE_SINGLE_SUCCESS = 'INVOICE_SINGLE_SUCCESS'
export const INVOICE_SINGLE_FALIURE = 'INVOICE_SINGLE_FALIURE'

//POST A INVOICE
export const INVOICE_ADD_REQUEST = 'INVOICE_ADD_REQUEST'
export const INVOICE_ADD_SUCCESS = 'INVOICE_ADD_SUCCESS'
export const INVOICE_ADD_FALIURE = 'INVOICE_ADD_FALIURE'

//POST A INVOICE-SERVICE
export const INVOICE_SERVICE_REQUEST = 'INVOICE_SERVICE_REQUEST'
export const INVOICE_SERVICE_SUCCESS = 'INVOICE_SERVICE_SUCCESS'
export const INVOICE_SERVICE_FALIURE = 'INVOICE_SERVICE_FALIURE'
